apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: stenote/nginx-hostname

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
  #type: LoadBalancer
  #loadBalancerIP: 192.168.56.107

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-app
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.example.com
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
            service:
              name: nginx-service
              port: 
                number: 80
